### ISSUE TITLE
forkしても大丈夫でしょうか？

### ISSUE THREAD

**Issue by RossyWhite** [nyatla/JZaif#1]
つい先日、先物取引のAPIをリリースしまして、
これを機に各言語のAPIラッパーを[techbureau](https://github.com/techbureau)のアカウントに集結させようと思っているのですが、  

差し支えなければ、このリポジトリをforkさせていただけないでしょうか？

**Comment by nyatla** [comment]
Forkしても大丈夫です。

ただし、このコードはずいぶん古いので、新しい通貨セット（トークン系）や信用などのAPIを使うことができません。

**Comment by RossyWhite** [comment]
ありがとうございます。
承知いたしました。

closeさせていただきますね。
